services:
  - type: web
    name: opencord-server
    runtime: node
    region: oregon
    plan: free

    buildCommand: npm install --include=dev && npm run build -w server
    startCommand: node server/dist/index.js

    envVars:
      - key: NODE_VERSION
        value: "24.7.0"

      - key: NODE_ENV
        value: production

      - key: PORT
        value: "10000"

      - key: TRUST_PROXY
        value: "1"

      - key: COOKIE_SECURE
        value: "true"

      - key: PUBLIC_URL
        value: "https://opencordweb.vercel.app"

      - key: ALLOWED_ORIGINS
        value: "https://opencordweb.vercel.app"
